CONFIG_ZMK_KEYBOARD_NAME="Corchibi"
CONFIG_ZMK_POINTING=y
CONFIG_PINCTRL=y
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_INPUT=y

CONFIG_PAT9125=y

CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_PHY_2M=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# ————— 親機(Central)の強制指定（BLE通信プログラムをオンにする） —————
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=n
CONFIG_ZMK_SPLIT_BLE_ROLE_PERIPHERAL=n
# ————————————————————————————————————————————————

# ————— DYA Studio 親機(Central)必須設定 —————
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_TRANSPORT_BLE=y

CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR_STUDIO_RPC=y

CONFIG_ZMK_BLE_MANAGEMENT=y
CONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=y

CONFIG_ZMK_BATTERY_HISTORY=y
CONFIG_ZMK_BATTERY_HISTORY_STUDIO_RPC=y

CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SETTINGS_RPC_STUDIO=y

CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_SETTINGS=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000
# ————————————————————————————————————————————

CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS=y
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

CONFIG_BT_BUF_ACL_TX_COUNT=16
CONFIG_BT_BUF_EVT_RX_COUNT=20

CONFIG_NFCT_PINS_AS_GPIOS=y

CONFIG_ZMK_USB_LOGGING=n
CONFIG_LOG=n
CONFIG_SHELL=n
CONFIG_I2C_SHELL=n

CONFIG_ZMK_BLE_THREAD_STACK_SIZE=3072
CONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=3072
CONFIG_INPUT_THREAD_STACK_SIZE=3072
CONFIG_ZMK_SPLIT_BLE_PERIPHERAL_STACK_SIZE=3072

CONFIG_ZMK_INPUT_PROCESSOR_ACCELERATION=y
CONFIG_INPUT_PROCESSOR_ACCEL_LEVEL_STANDARD=y
CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_CUSTOM=y

CONFIG_ZMK_INSOMNIA_PING_ON_START=y
CONFIG_ZMK_INSOMNIA_PING_INTERVAL=15000