CONFIG_ZMK_KEYBOARD_NAME="Corchibi"

# Hardware / Trackball
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_PINCTRL=y
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_INPUT=y
CONFIG_PAT9125=y
CONFIG_NFCT_PINS_AS_GPIOS=y

# Bluetooth Connections
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# Split & Battery
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# DYA Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_BLE_MANAGEMENT=y
CONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR_STUDIO_RPC=y
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SETTINGS_RPC_STUDIO=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_SETTINGS=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000

# Behaviors
CONFIG_ZMK_INPUT_PROCESSOR_ACCELERATION=y
CONFIG_INPUT_PROCESSOR_ACCEL_LEVEL_STANDARD=y
CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_CUSTOM=y
CONFIG_ZMK_INSOMNIA_PING_ON_START=y
CONFIG_ZMK_INSOMNIA_PING_INTERVAL=15000

# 起動クラッシュ防止（メモリ枠の拡張）
CONFIG_ZMK_BLE_THREAD_STACK_SIZE=3072
CONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=3072
CONFIG_INPUT_THREAD_STACK_SIZE=3072
CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=1024

# Compiler Fixes
CONFIG_COMPILER_WARNINGS_AS_ERRORS=n