# --- Hardware & Pointing ---
CONFIG_ZMK_POINTING=y
CONFIG_PINCTRL=y
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_INPUT=y
CONFIG_PAT9125=y
CONFIG_NFCT_PINS_AS_GPIOS=y

# --- DYA Studio (子機側必須設定) ---
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_SETTINGS=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000